-- ============================================
-- Seed: Inventory (Warehouses and initial Stock)
-- Note: Only warehouses and stock levels, NOT movements
-- Movements are generated by business logic (purchases, sales, etc.)
-- ============================================

-- Clear existing data (stocks depend on warehouses)
DELETE FROM stocks;
DELETE FROM warehouses;

-- Warehouses
INSERT INTO warehouses (code, name, ubigeo_id, address, is_active) VALUES
('ALM-LIMA-01', 'Almacén Central Lima', '150101', 'Av. Argentina 1234, Cercado de Lima', true),
('ALM-LIMA-02', 'Almacén San Isidro', '150131', 'Calle Las Begonias 456, San Isidro', true),
('ALM-CALLAO', 'Almacén Callao', '070101', 'Av. Sáenz Peña 789, Callao', true),
('ALM-AQP', 'Almacén Arequipa', '040101', 'Calle Mercaderes 321, Arequipa', true);

-- Initial stock levels (only for variants that exist)
-- This simulates initial inventory without generating movements
-- Real movements should be created by purchase receipts in the backend

INSERT INTO stocks (warehouse_id, variant_id, quantity, reserved_quantity)
SELECT w.id, v.id, 
       CASE 
           WHEN w.code = 'ALM-LIMA-01' THEN 50  -- Main warehouse has most stock
           WHEN w.code = 'ALM-LIMA-02' THEN 20
           ELSE 10
       END,
       0
FROM warehouses w
CROSS JOIN variants v
WHERE w.code IN ('ALM-LIMA-01', 'ALM-LIMA-02', 'ALM-AQP')
AND v.is_active = true;
